
package flows.WebserviceClients.tempconvert.com.w3schools.webservices;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import flows.WebserviceClients.tempconvert.com.w3schools.webservices.TempConvert;

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.0.0-milestone2
 * 2014-03-06T18:18:06.281+05:30
 * Generated source version: 3.0.0-milestone2
 * 
 */
public final class TempConvertSoap_TempConvertSoap_Client {

    private static final QName SERVICE_NAME = new QName("http://www.w3schools.com/webservices/", "TempConvert");

    private TempConvertSoap_TempConvertSoap_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = TempConvert.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        TempConvert ss = new TempConvert(wsdlURL, SERVICE_NAME);
        TempConvertSoap port = ss.getTempConvertSoap();  
        
        {
        System.out.println("Invoking fahrenheitToCelsius...");
        java.lang.String _fahrenheitToCelsius_fahrenheit = "35";
        java.lang.String _fahrenheitToCelsius__return = port.fahrenheitToCelsius(_fahrenheitToCelsius_fahrenheit);
        System.out.println("fahrenheitToCelsius.result=" + _fahrenheitToCelsius__return);


        }
        {
        System.out.println("Invoking celsiusToFahrenheit...");
        java.lang.String _celsiusToFahrenheit_celsius = "45";
        java.lang.String _celsiusToFahrenheit__return = port.celsiusToFahrenheit(_celsiusToFahrenheit_celsius);
        System.out.println("celsiusToFahrenheit.result=" + _celsiusToFahrenheit__return);


        }

        System.exit(0);
    }

}
