package flows.webserviceClients.periodicTable.net.webservicex;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.0.0-milestone2
 * 2014-03-06T16:22:30.936+05:30
 * Generated source version: 3.0.0-milestone2
 * 
 */
@WebService(targetNamespace = "http://www.webserviceX.NET", name = "periodictableHttpPost")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface PeriodictableHttpPost {

    /**
     * Get atomic Number by element name 
     */
    @WebResult(name = "string", targetNamespace = "http://www.webserviceX.NET", partName = "Body")
    @WebMethod(operationName = "GetAtomicNumber")
    public java.lang.String getAtomicNumber(
        @WebParam(partName = "ElementName", name = "ElementName", targetNamespace = "http://www.webserviceX.NET")
        java.lang.String elementName
    );

    /**
     * Get atomic symbol by element name 
     */
    @WebResult(name = "string", targetNamespace = "http://www.webserviceX.NET", partName = "Body")
    @WebMethod(operationName = "GetElementSymbol")
    public java.lang.String getElementSymbol(
        @WebParam(partName = "ElementName", name = "ElementName", targetNamespace = "http://www.webserviceX.NET")
        java.lang.String elementName
    );

    /**
     * Get element 
     */
    @WebResult(name = "string", targetNamespace = "http://www.webserviceX.NET", partName = "Body")
    @WebMethod(operationName = "GetAtoms")
    public java.lang.String getAtoms();

    /**
     * Get atomic wieght by element name 
     */
    @WebResult(name = "string", targetNamespace = "http://www.webserviceX.NET", partName = "Body")
    @WebMethod(operationName = "GetAtomicWeight")
    public java.lang.String getAtomicWeight(
        @WebParam(partName = "ElementName", name = "ElementName", targetNamespace = "http://www.webserviceX.NET")
        java.lang.String elementName
    );
}
