
package flows.webserviceClients.currencyConvertor.net.webservices;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "CurrencyConvertor", targetNamespace = "http://www.webserviceX.NET/", wsdlLocation = "http://www.webservicex.net/CurrencyConvertor.asmx?WSDL")
public class CurrencyConvertor
    extends Service
{

    private final static URL CURRENCYCONVERTOR_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(flows.webserviceClients.currencyConvertor.net.webservices.CurrencyConvertor.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = flows.webserviceClients.currencyConvertor.net.webservices.CurrencyConvertor.class.getResource(".");
            url = new URL(baseUrl, "http://www.webservicex.net/CurrencyConvertor.asmx?WSDL");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'http://www.webservicex.net/CurrencyConvertor.asmx?WSDL', retrying as a local file");
            logger.warning(e.getMessage());
        }
        CURRENCYCONVERTOR_WSDL_LOCATION = url;
    }

    public CurrencyConvertor(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public CurrencyConvertor() {
        super(CURRENCYCONVERTOR_WSDL_LOCATION, new QName("http://www.webserviceX.NET/", "CurrencyConvertor"));
    }

    /**
     * 
     * @return
     *     returns CurrencyConvertorSoap
     */
    @WebEndpoint(name = "CurrencyConvertorSoap")
    public CurrencyConvertorSoap getCurrencyConvertorSoap() {
        return super.getPort(new QName("http://www.webserviceX.NET/", "CurrencyConvertorSoap"), CurrencyConvertorSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns CurrencyConvertorSoap
     */
    @WebEndpoint(name = "CurrencyConvertorSoap")
    public CurrencyConvertorSoap getCurrencyConvertorSoap(WebServiceFeature... features) {
        return super.getPort(new QName("http://www.webserviceX.NET/", "CurrencyConvertorSoap"), CurrencyConvertorSoap.class, features);
    }

    /**
     * 
     * @return
     *     returns CurrencyConvertorSoap
     */
    @WebEndpoint(name = "CurrencyConvertorSoap12")
    public CurrencyConvertorSoap getCurrencyConvertorSoap12() {
        return super.getPort(new QName("http://www.webserviceX.NET/", "CurrencyConvertorSoap12"), CurrencyConvertorSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns CurrencyConvertorSoap
     */
    @WebEndpoint(name = "CurrencyConvertorSoap12")
    public CurrencyConvertorSoap getCurrencyConvertorSoap12(WebServiceFeature... features) {
        return super.getPort(new QName("http://www.webserviceX.NET/", "CurrencyConvertorSoap12"), CurrencyConvertorSoap.class, features);
    }

    /**
     * 
     * @return
     *     returns CurrencyConvertorHttpGet
     */
    @WebEndpoint(name = "CurrencyConvertorHttpGet")
    public CurrencyConvertorHttpGet getCurrencyConvertorHttpGet() {
        return super.getPort(new QName("http://www.webserviceX.NET/", "CurrencyConvertorHttpGet"), CurrencyConvertorHttpGet.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns CurrencyConvertorHttpGet
     */
    @WebEndpoint(name = "CurrencyConvertorHttpGet")
    public CurrencyConvertorHttpGet getCurrencyConvertorHttpGet(WebServiceFeature... features) {
        return super.getPort(new QName("http://www.webserviceX.NET/", "CurrencyConvertorHttpGet"), CurrencyConvertorHttpGet.class, features);
    }

    /**
     * 
     * @return
     *     returns CurrencyConvertorHttpPost
     */
    @WebEndpoint(name = "CurrencyConvertorHttpPost")
    public CurrencyConvertorHttpPost getCurrencyConvertorHttpPost() {
        return super.getPort(new QName("http://www.webserviceX.NET/", "CurrencyConvertorHttpPost"), CurrencyConvertorHttpPost.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns CurrencyConvertorHttpPost
     */
    @WebEndpoint(name = "CurrencyConvertorHttpPost")
    public CurrencyConvertorHttpPost getCurrencyConvertorHttpPost(WebServiceFeature... features) {
        return super.getPort(new QName("http://www.webserviceX.NET/", "CurrencyConvertorHttpPost"), CurrencyConvertorHttpPost.class, features);
    }

}
