
package flows.webserviceClients.periodicTable;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.0.0-milestone2
 * 2014-03-14T14:08:52.151+05:30
 * Generated source version: 3.0.0-milestone2
 * 
 */
public final class PeriodictableSoap_PeriodictableSoap_Client {

    private static final QName SERVICE_NAME = new QName("http://www.webserviceX.NET", "periodictable");

    private PeriodictableSoap_PeriodictableSoap_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = Periodictable.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        Periodictable ss = new Periodictable(wsdlURL, SERVICE_NAME);
        PeriodictableSoap port = ss.getPeriodictableSoap();  
        
        {
        System.out.println("Invoking getAtomicNumber...");
        java.lang.String _getAtomicNumber_elementName = "";
        java.lang.String _getAtomicNumber__return = port.getAtomicNumber(_getAtomicNumber_elementName);
        System.out.println("getAtomicNumber.result=" + _getAtomicNumber__return);


        }
        {
        System.out.println("Invoking getElementSymbol...");
        java.lang.String _getElementSymbol_elementName = "";
        java.lang.String _getElementSymbol__return = port.getElementSymbol(_getElementSymbol_elementName);
        System.out.println("getElementSymbol.result=" + _getElementSymbol__return);


        }
        {
        System.out.println("Invoking getAtoms...");
        java.lang.String _getAtoms__return = port.getAtoms();
        System.out.println("getAtoms.result=" + _getAtoms__return);


        }
        {
        System.out.println("Invoking getAtomicWeight...");
        java.lang.String _getAtomicWeight_elementName = "";
        java.lang.String _getAtomicWeight__return = port.getAtomicWeight(_getAtomicWeight_elementName);
        System.out.println("getAtomicWeight.result=" + _getAtomicWeight__return);


        }

        System.exit(0);
    }

}
