
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package flows.webserviceClients.currencyConvertor.net.webservicex;

import java.util.logging.Logger;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.0.0-milestone2
 * 2014-03-05T09:28:40.599+05:30
 * Generated source version: 3.0.0-milestone2
 * 
 */

@javax.jws.WebService(
                      serviceName = "CurrencyConvertor",
                      portName = "CurrencyConvertorSoap12",
                      targetNamespace = "http://www.webserviceX.NET/",
                      wsdlLocation = "http://www.webservicex.net/CurrencyConvertor.asmx?WSDL",
                      endpointInterface = "net.webservicex.CurrencyConvertorSoap")
                      
public class CurrencyConvertorSoap12Impl implements CurrencyConvertorSoap {

    private static final Logger LOG = Logger.getLogger(CurrencyConvertorSoap12Impl.class.getName());

    /* (non-Javadoc)
     * @see net.webservicex.CurrencyConvertorSoap#conversionRate(net.webservicex.Currency  fromCurrency ,)net.webservicex.Currency  toCurrency )*
     */
    public double conversionRate(Currency fromCurrency,Currency toCurrency) {
        LOG.info("Executing operation conversionRate");
        System.out.println(fromCurrency);
        System.out.println(toCurrency);
        try {
            double _return = 0.0;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

}
