package businessLayer.webserviceClients.periodicTable;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.0.0-milestone2
 * 2014-03-14T14:08:52.186+05:30
 * Generated source version: 3.0.0-milestone2
 * 
 */
@WebService(targetNamespace = "http://www.webserviceX.NET", name = "periodictableSoap")
@XmlSeeAlso({ObjectFactory.class})
public interface PeriodictableSoap {

    /**
     * Get atomic Number by element name 
     */
    @WebResult(name = "GetAtomicNumberResult", targetNamespace = "http://www.webserviceX.NET")
    @RequestWrapper(localName = "GetAtomicNumber", targetNamespace = "http://www.webserviceX.NET", className = "businessLayer.webserviceClients.periodicTable.GetAtomicNumber")
    @WebMethod(operationName = "GetAtomicNumber", action = "http://www.webserviceX.NET/GetAtomicNumber")
    @ResponseWrapper(localName = "GetAtomicNumberResponse", targetNamespace = "http://www.webserviceX.NET", className = "businessLayer.webserviceClients.periodicTable.GetAtomicNumberResponse")
    public java.lang.String getAtomicNumber(
        @WebParam(name = "ElementName", targetNamespace = "http://www.webserviceX.NET")
        java.lang.String elementName
    );

    /**
     * Get atomic symbol by element name 
     */
    @WebResult(name = "GetElementSymbolResult", targetNamespace = "http://www.webserviceX.NET")
    @RequestWrapper(localName = "GetElementSymbol", targetNamespace = "http://www.webserviceX.NET", className = "businessLayer.webserviceClients.periodicTable.GetElementSymbol")
    @WebMethod(operationName = "GetElementSymbol", action = "http://www.webserviceX.NET/GetElementSymbol")
    @ResponseWrapper(localName = "GetElementSymbolResponse", targetNamespace = "http://www.webserviceX.NET", className = "businessLayer.webserviceClients.periodicTable.GetElementSymbolResponse")
    public java.lang.String getElementSymbol(
        @WebParam(name = "ElementName", targetNamespace = "http://www.webserviceX.NET")
        java.lang.String elementName
    );

    /**
     * Get element 
     */
    @WebResult(name = "GetAtomsResult", targetNamespace = "http://www.webserviceX.NET")
    @RequestWrapper(localName = "GetAtoms", targetNamespace = "http://www.webserviceX.NET", className = "businessLayer.webserviceClients.periodicTable.GetAtoms")
    @WebMethod(operationName = "GetAtoms", action = "http://www.webserviceX.NET/GetAtoms")
    @ResponseWrapper(localName = "GetAtomsResponse", targetNamespace = "http://www.webserviceX.NET", className = "businessLayer.webserviceClients.periodicTable.GetAtomsResponse")
    public java.lang.String getAtoms();

    /**
     * Get atomic wieght by element name 
     */
    @WebResult(name = "GetAtomicWeightResult", targetNamespace = "http://www.webserviceX.NET")
    @RequestWrapper(localName = "GetAtomicWeight", targetNamespace = "http://www.webserviceX.NET", className = "businessLayer.webserviceClients.periodicTable.GetAtomicWeight")
    @WebMethod(operationName = "GetAtomicWeight", action = "http://www.webserviceX.NET/GetAtomicWeight")
    @ResponseWrapper(localName = "GetAtomicWeightResponse", targetNamespace = "http://www.webserviceX.NET", className = "businessLayer.webserviceClients.periodicTable.GetAtomicWeightResponse")
    public java.lang.String getAtomicWeight(
        @WebParam(name = "ElementName", targetNamespace = "http://www.webserviceX.NET")
        java.lang.String elementName
    );
}
